[package]
edition = "2021"
name = "farm_plugin_yaml"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
serde_yaml = "0.9.34"
lazy_static = "1.5.0"
serde = "1.0.203"
globset = "0.4.14"
regex = "1.10.5"
